[package]
name = "multi-creator-collection"
authors = ["Starty Team"]
description = "CW721 collection with per-token creator royalties"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
library = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
cw2.workspace = true
cw721.workspace = true
cw721-base = { workspace = true, features = ["library"] }
cw-storage-plus.workspace = true
cw-ownable.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
cw-multi-test = "2.3.0"
